//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _004_15Repetitor_26_01_23.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment
    {
        public int Id { get; set; }
        public int IdRep { get; set; }
        public int IdStud { get; set; }
        public System.TimeSpan StartTime { get; set; }
        public System.TimeSpan EndTime { get; set; }
        public string Description { get; set; }
        public int IdLesson { get; set; }
    
        public virtual Lesson Lesson { get; set; }
        public virtual Repetitor Repetitor { get; set; }
        public virtual Student Student { get; set; }
    }
}
